# Generated by Django 6.0 on 2025-12-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, help_text='Human-readable order reference', max_length=50, unique=True),
        ),
    ]
