# Generated by Django 6.0 on 2025-12-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, help_text='Human-readable order reference', max_length=32, unique=True),
        ),
    ]
