# Generated by Django 6.0 on 2025-12-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_city_order_country_order_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
    ]
