# Generated by Django 6.0 on 2025-12-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, help_text='State for the shipping address', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, default='Canada', help_text='Country for the shipping address', max_length=50, null=True),
        ),
    ]
