# Generated by Django 6.0 on 2025-12-22 19:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_state_alter_order_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax percent applied at purchase time', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
